name: Update Sponsors

on:
  workflow_dispatch:
  schedule:
    - cron: 0 8 * * *

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Generate Sponsors 💖
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.SPONSORS_TOKEN }}
          file: "README.md"
          active-only: false
        if: ${{ github.repository == 'ravitemer/mcphub.nvim' }}

      - name: Create Pull Request 🚀
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "docs: update sponsors in README.md"
          title: "docs: update sponsors in README.md"
          delete-branch: true
